net:
  backbone_pretrained: true
  backbone_freeze_batch_norm: true
  neck_attention_reduction: 16

image:
  train_min_sizes: [480, 560, 640, 720, 800, 880]
  test_min_size: 640
  max_size: 880
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

anchors:
  sizes:
    - [16]
    - [32]
    - [64]
    - [128]
    - [256]
  aspect_ratios:
    - [0.5, 1.0, 2.0]
    - [0.5, 1.0, 2.0]
    - [0.5, 1.0, 2.0]
    - [0.5, 1.0, 2.0]
    - [0.5, 1.0, 2.0]

proposal:
  positive_iou: 0.7
  negative_iou: 0.3

soft_nms:
  enabled: true
  method: linear
  iou_thresh: 0.5
  sigma: 0.5
  score_thresh: 0.001
