net:
  backbone_pretrained: true
  backbone_freeze_batch_norm: true

anchors:
  sizes:
    - [16]
    - [32]
    - [64]
    - [128]
    - [256]
  aspect_ratios:
    - [0.5, 1.0, 2.0]
    - [0.5, 1.0, 2.0]
    - [0.5, 1.0, 2.0]
    - [0.5, 1.0, 2.0]
    - [0.5, 1.0, 2.0]

proposal:
  positive_iou: 0.7
  negative_iou: 0.3

soft_nms:
  enabled: true
  method: linear
  iou_thresh: 0.5
  sigma: 0.5
  score_thresh: 0.001
